security:
    encoders:
        Hes\Bundle\IndiaBundle\Entity\User:
            algorithm: sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
         users:
            entity: { class: HESIndiaBundle:User, property: userEmail }

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  hes_welcome-page
                check_path:  login_check
                default_target_path: list_ticket
            logout:
                path: log_out

    access_control:
       - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
      #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }